name: E2E QA Automation CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Much shorter timeout for debugging
    
    strategy:
      matrix:
        node-version: [20.x]  # Single Node version
        browser: [chromium]   # Single browser for debugging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
      env:
        PLAYWRIGHT_BROWSERS_PATH: 0
      
    - name: Create test results directory
      run: mkdir -p test-results/screenshots allure-results
      
    - name: Run only debug tests
      run: npx playwright test tests/debug-ci.spec.ts --project=${{ matrix.browser }} --timeout=60000 --workers=1
      env:
        CI: true
        BASE_URL: https://demoqa.com
        DEBUG: pw:api
        PLAYWRIGHT_BROWSERS_PATH: 0
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.browser }}-${{ matrix.node-version }}
        path: |
          test-results/
          allure-results/
        retention-days: 30

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run TypeScript type check
      run: npm run type-check

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      
    - name: Run Snyk security scan
      continue-on-error: true
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

  notify:
    runs-on: ubuntu-latest
    needs: [test, lint, security]
    if: ${{ always() && secrets.SLACK_WEBHOOK_URL != '' }}
    timeout-minutes: 2
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
    - name: Notify on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: 'E2E QA Automation tests failed! Check the logs for details.'
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        github_token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Notify on success
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: 'E2E QA Automation tests passed successfully! 🎉'
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        github_token: ${{ secrets.GITHUB_TOKEN }} 